import type { Site, SocialObjects } from "./types";

export const SITE: Site = {
  website: "https://aziflaj.github.io/", // replace this with your deployed domain
  author: "Aldo Ziflaj",
  profile: "https://aziflaj.github.io/",
  desc: "Randomly Generated Bytes, marshalled in Human-readable format",
  title: "aziflaj",
  ogImage: "astropaper-og.jpg",
  lightAndDarkMode: true,
  postPerIndex: 6,
  postPerPage: 6,
  scheduledPostMargin: 15 * 60 * 1000, // 15 minutes
  showArchives: false,
};

export const LOCALE = {
  lang: "en", // html lang code. Set this empty and default will be "en"
  langTag: ["en-EN"], // BCP 47 Language Tags. Set this empty [] to use the environment default
} as const;

export const LOGO_IMAGE = {
  enable: false,
  svg: true,
  width: 216,
  height: 46,
};

export const SOCIALS: SocialObjects = [
  {
    name: "Github",
    href: "https://github.com/aziflaj",
    linkTitle: `My Github`,
    active: true,
  },
  {
    name: "LinkedIn",
    href: "https://linkedin.com/in/aziflaj",
    linkTitle: `My LinkedIn`,
    active: true,
  },
];
